# essentials
harmonised_list: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/harmonised_list.txt
repository_path: /data/tools/gwas_base_utils
working_directory: /data/DeleteMe
maf_file: /data/references/1000Genome/reference/EUR/eur_hg38.phase3.frq

#filter studies
efoIds: DeleteMe.txt
filter_study_output: test_studies.txt

#transform
tansform_study_input: test_studies.txt
transformed_path: /data/DeleteMe/transformed

# Pre-processing
target_data: /data/DeleteMe/target_data
remove_samples: /data/DeleteMe/empty_remove_samples.txt
processed_data_name: data_xxx_maf_001
convert_rsid: TRUE
maf: 0.01

# PRS calculation
# essentials
studies_to_calculate: test_studies.txt
results_name: test_prs
preprocessed_target_data: /data/DeleteMe/target_data/corrected_hg38/EUR/EUR.FINAL

#PRSice
ld_reference: /data/1000Genome/reference/EUR/eur_hg38.phase3
clump_kb: 500
clump_p: 1
clump_r2: 0.2
prsice_default_maf: 0.01

#LDpred2
mode : auto # or inf
imputation_mode : random
max_threads: 3
ldpred2_ref: /data/references/ldpred2_ref # clone : https://github.com/comorment/ldpred2_ref

#information about imputation : https://privefl.github.io/bigsnpr/reference/snp_fastImputeSimple.html
# Either "random" (sampling according to allele frequencies), "mean0" (rounded mean), "mean2" (rounded mean to 2 decimal places), "mode" (most frequent call).
