name: pgscope
channels:
  - conda-forge
  - bioconda
  - dnachun
dependencies:
  - r-base
  - r-essentials
  - r-gwasrapidd
  - plink
  - plink2
  - r-plinkqc
  - prsice
  - r-bigsnpr
  - r-argparser
