target_data:
genotype_data_name:  # without extension [bim,bed,fam]
output_path:
processed_data_directory_name:
convert_rsid: TRUE # if true, convert to CHR:POS format
shallow_genotype_missingness: 0.2
deep_genotype_missingness: 0.02
shallow_sample_missingness: 0.2
deep_sample_missingness: 0.02
maf: 0.005
hwe: 1e-6
heterozygosity: 3 # Threshold for acceptable deviation from mean heterozygosity per individual.
relatedness: 0.1875 #Threshold for acceptable proportion of IBD between pair of individuals.

