studies_to_calculate_ldpred: # GWAS ids txt
results_path_ldpred:
results_directory_name_ldpred:
results_data_table_name_ldpred:
mode : auto # or inf
imputation_mode : random
ldpred2_ref:
target_data_path_ldpred:
target_data_prefix_ldpred:  # name without extension (bim,bed,fam)
gwas_data_path_ldpred:
ldpred_path:     # default is repository/main/tools/ldpred2
intercept_max: 1.2
intercept_min: 0.95
heritability: 0.01
hyper_p_max: 0.9
