# GWAS search module
efo_ids: input/efo_ids.txt
output_path_gwas_search: output/gwas_list
output_name_gwas_search: gwas_search
sample_size: 10000
population: European
number_of_snps: 250000
publication_date: 2018-01-01
harmonised_list: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/harmonised_list.txt

# GWAS QC module
study_list: output/gwas_list/gwas_search.txt
output_path_qced_gwas: output/qced_gwas
maf_file: input/reference/eur_hg38.phase3.frq

# Genotpye QC module
target_data: input/genotype
genotype_data_name: EUR
output_path: output/qced_genotype
processed_data_directory_name: data_test_0005
convert_rsid: TRUE
shallow_genotype_missingness: 0.2
deep_genotype_missingness: 0.02
shallow_sample_missingness: 0.2
deep_sample_missingness: 0.02
maf: 0.005
hwe: 1e-6
heterozygosity: 3 # Threshold for acceptable deviation from mean heterozygosity per individual.
relatedness: 0.1875 #Threshold for acceptable proportion of IBD between pair of individuals.

# PGS calculation PRSice
studies_to_calculate: output/gwas_list/gwas_search.txt
results_path: output
results_directory_name: calculated_pgs_prsice
results_data_table_name: pgs_datatable_prsice
target_data_path: output/qced_genotype/corrected_hg38/data_test_0005
target_data_prefix: EUR.FINAL # name without extension (bim,bed,fam)
gwas_data_path: output/qced_gwas
clumping_reference_path: input/reference
clumping_reference_prefix: eur_hg38.phase3 # name without extension (bim,bed,fam)
clump_kb: 500
clump_p: 1
clump_r2: 0.2
base_maf: 0.01
p_values: "0.00000005,0.0000001,0.000001,0.00001,0.0001,0.001,0.01,0.05,0.1,0.5,1"
min_number_of_snps_included: 100
min_number_of_snps_included_of_the_highest_p_value: 1000

# PGS calculation LDpred
studies_to_calculate_ldpred: output/gwas_list/gwas_search.txt
results_path_ldpred: output
results_directory_name_ldpred: calculated_pgs_ldpred
results_data_table_name_ldpred: pgs_datatable_ldpred
mode : auto # or inf
imputation_mode : random
ldpred2_ref: /data/references/ldpred2_ref # clone : https://github.com/comorment/ldpred2_ref
target_data_path_ldpred: output/qced_genotype/corrected_hg38/data_test_0005
target_data_prefix_ldpred: EUR.FINAL # name without extension (bim,bed,fam)
gwas_data_path_ldpred: output/qced_gwas
ldpred_path:     # default is repository/main/tools/PRSice
intercept_max: 1.2
intercept_min: 0.95
heritability: 0.01
hyper_p_max: 0.9
