# GWAS search module
efo_ids: input/efo_ids.txt
output_path_gwas_search: output/gwas_list
output_name_gwas_search: gwas_search
sample_size: 10000
population: European
number_of_snps: 250000
publication_date: 2018-01-01
harmonised_list: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/harmonised_list.txt

# GWAS QC module
study_list: output/gwas_list/gwas_search.txt.tsv
output_path_qced_gwas: output/qced_gwas
maf_file: input/reference/eur_hg38.phase3.frq
number_of_snps_after_qc: 250000
pubmed_ids_to_exclude: 34662886
number_of_cases: 5000

# Heritability
study_list_for_heritability: output/gwas_list/gwas_search.txt.tsv.qced
gwas_data_path_heritability: output/qced_gwas
hm3_path: input/reference/ldscore/eur_w_ld_chr/w_hm3.snplist
ldsc_path: # default is repository/main/tools/ldsc
chunksize: 100000
ld_ref: input/reference/ldscore/eur_w_ld_chr_hg38
heritability_min_zscore: 4
output_path_heritability: output/heritability

# Genetic Correlation
study_list_for_genetic_correlation: output/gwas_list/gwas_search.txt.tsv.qced.heritability
gwas_data_path_genetic_correlation: output/qced_gwas
ldsc_path: # default is repository/main/tools/ldsc
ld_ref: input/reference/ldscore/eur_w_ld_chr_hg38
output_path_genetic_correlation: output/genetic_correlation
rg_thr: 0.98
chunksize_gen_cor: 100000
hm3_path_gen_cor: input/reference/ldscore/eur_w_ld_chr/w_hm3.snplist

# Genotpye QC module
target_data: input/genotype
genotype_data_name: EUR
output_path: output/qced_genotype
processed_data_directory_name: data_test_0005
convert_rsid: TRUE
shallow_genotype_missingness: 0.2
deep_genotype_missingness: 0.02
shallow_sample_missingness: 0.2
deep_sample_missingness: 0.02
maf: 0.005
hwe: 1e-6
heterozygosity: 3 # Threshold for acceptable deviation from mean heterozygosity per individual.
relatedness: 0.1875 #Threshold for acceptable proportion of IBD between pair of individuals.

# PGS calculation PRSice
studies_to_calculate: output/gwas_list/gwas_search.txt
results_path: output
results_directory_name: calculated_pgs_prsice
results_data_table_name: pgs_datatable_prsice
target_data_path: output/qced_genotype/corrected_hg38/data_test_0005
target_data_prefix: EUR.FINAL # name without extension (bim,bed,fam)
gwas_data_path: output/qced_gwas
clumping_reference_path: input/reference
clumping_reference_prefix: eur_hg38.phase3 # name without extension (bim,bed,fam)
clump_kb: 500
clump_p: 1
clump_r2: 0.2
base_maf: 0.01
p_values: "0.00000005,0.0000001,0.000001,0.00001,0.0001,0.001,0.01,0.05,0.1,0.5,1"
min_number_of_snps_included: 100
min_number_of_snps_included_of_the_highest_p_value: 1000

# PGS calculation LDpred
studies_to_calculate_ldpred: output/gwas_list/gwas_search.txt
results_path_ldpred: output
results_directory_name_ldpred: calculated_pgs_ldpred
results_data_table_name_ldpred: pgs_datatable_ldpred
mode : auto # or inf
imputation_mode : random
ldpred2_ref: /data/references/ldpred2_ref # clone : https://github.com/comorment/ldpred2_ref
target_data_path_ldpred: /data/projects/on_going/CoviDrug/TRR/target/corrected_hg38/data_TRR_maf_0005/overlap
target_data_prefix_ldpred: trr_overlap # name without extension (bim,bed,fam)
gwas_data_path_ldpred: /data/sumstats/transformed
ldpred_path:     # default is repository/main/tools/ldpred2
intercept_max: 1.2
intercept_min: 0.95
heritability: 0.01
hyper_p_max: 0.9
