studies_to_calculate:
results_path:
results_directory_name:
results_data_table_name:
target_data_path:
target_data_prefix:  # name without extension (bim,bed,fam)
gwas_data_path:
prsice_path:       # default is repository/main/tools/PRSice
clumping_reference_path:
clumping_reference_prefix:  # name without extension (bim,bed,fam)
clump_kb: 500
clump_p: 1
clump_r2: 0.2
base_maf: 0.01
p_values: "0.05,0.1,0.5,1"
min_number_of_snps_included: 100
min_number_of_snps_included_of_the_highest_p_value: 1000
