# GWAS search module
efo_ids: /data/projects/on_going/PRScope/input/efo_ids.txt
output_path_gwas_search: /data/projects/on_going/PRScope/output/gwas_list
output_name_gwas_search: gwas_search
sample_size: 10000
population: European
number_of_snps: 250000
publication_date: 2018-01-01
harmonised_list: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/harmonised_list.txt

# GWAS QC module
study_list: /data/projects/on_going/PRScope/output/gwas_list/gwas_search.txt
output_path_qced_gwas: /data/projects/on_going/PRScope/output/qced_gwas
maf_file: /data/projects/on_going/PRScope/input/reference/eur_hg38.phase3.frq

# Genotpye QC module
target_data: /data/projects/on_going/PRScope/input/genotype
genotype_data_name: EUR
output_path: /data/projects/on_going/PRScope/output/qced_genotype
processed_data_directory_name: data_test_0005
convert_rsid: TRUE
maf: 0.005
plink:         # default is repository/main/tools/plink
plink2:          # default is repository/main/tools/plink2
shallow_genotype_missingness: 0.2
deep_genotype_missingness: 0.02
shallow_sample_missingness: 0.2
deep_sample_missingness: 0.02
maf: 0.005
hwe: 1e-6
heterozygosity: 3 # Threshold for acceptable deviation from mean heterozygosity per individual.
relatedness: 0.1875 #Threshold for acceptable proportion of IBD between pair of individuals.

# PGS calculation
studies_to_calculate: /data/projects/on_going/PRScope/output/gwas_list/gwas_search.txt
results_path: /data/projects/on_going/PRScope/output
results_directory_name: calculated_pgs
results_data_table_name: all_pgs_datatable
target_data_path: /data/projects/on_going/PRScope/output/qced_genotype/corrected_hg38/data_test_0005
target_data_prefix: test_2.FINAL # name without extension (bim,bed,fam)
gwas_data_path: /data/projects/on_going/PRScope/output/qced_gwas
prsice_path:        # default is repository/main/tools/PRSice
clumping_reference_path: /data/projects/on_going/PRScope/input/reference
clumping_reference_prefix: eur_hg38.phase3 # name without extension (bim,bed,fam)
clump_kb: 500
clump_p: 1
clump_r2: 0.2
base_maf: 0.01
p_values: "0.05,0.1,0.5,1"
min_number_of_snps_included: 100
min_number_of_snps_included_of_the_highest_p_value: 1000
