rm(list=ls())
gc()
library(data.table)
args = commandArgs(trailingOnly=TRUE)
input <- args[1]

sample_missingness <- fread(sprintf("%s.smiss",input), header = T)
snp_missingness <- fread(sprintf("%s.vmiss",input), header = T)
freq <- fread(sprintf("%s.afreq",input), header = T)
het <- fread(sprintf("%s.het",input),header = T)
jpeg(sprintf("%s.sample_missingness.jpeg",input))
hist(as.numeric(sample_missingness$F_MISS))
dev.off()
jpeg(sprintf("%s.snp_missingness.jpeg",input))
hist(as.numeric(snp_missingness$F_MISS))
dev.off()
jpeg(sprintf("%s.frq.jpeg",input))
hist(as.numeric(freq$ALT_FREQS),main = "MAF distribution", xlab = "MAF")
dev.off()
jpeg(sprintf("%s.het.jpeg",input))
hist(as.numeric(het$F),main = "Het distribution", xlab = "het")
dev.off()
